[package]
name = "fsspec_rs"
version = "0.1.5"
authors = ["the fsspec-rs authors <dev@1kbgz.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/1kbgz/fsspec-rs"
description = "fsspec-compatible backends with Rust acceleration"

[lib]
name = "fsspec_rs"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
object_store = { version = "0.12", features = ["aws"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
bytes = "1"
url = "2"

[dev-dependencies]
tempfile = "3"

[workspace]
members = [
    ".",
    "bridge",
]
