[package]
name = "fsspec_rs"
version = "0.1.0"
authors = ["the fsspec-rs authors <dev@1kbgz.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/1kbgz/fsspec-rs"
description = ""

[lib]
name = "fsspec_rs"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]

[profile.test.junit]
path = "junit.xml"

