
.PHONY: requirements develop build
requirements:  ## install required dev dependencies
	rustup component add rustfmt
	rustup component add clippy
	cargo install --locked --force cargo-nextest
	cargo install --force cargo-llvm-cov

develop: requirements  ## install required dev dependencies

build:  ## build release
	cargo build --workspace --release --all-features

.PHONY: lint lints fix format
lint:  ## run Clippy for linting, rustfmt for autoformat checks
	cargo clippy --workspace --all-features
	cargo fmt --all -- --check
# alias
lints: lint

fix:  ## fix code with rustfmt
	cargo fmt --all
#alias
format: fix

.PHONY: check checks
check:
	cargo check --workspace --all-features
# alias
checks: check

.PHONY: test tests test-ci tests-ci
test:  ## run the tests
	cargo llvm-cov nextest --workspace --cobertura --output-path  junit.xml

# alias
tests: test

coverage:
	cargo llvm-cov nextest --workspace --lcov --output-path coverage

.PHONY: dist publish
dist:  ## create dist
	cargo publish --workspace --dry-run --allow-dirty

publish:  ## publish to cargo
	cargo publish --workspace

# Thanks to Francoise at marmelab.com for this
.DEFAULT_GOAL := help
help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

print-%:
	@echo '$*=$($*)'
